name: CI

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t visibilityspots/gotify-cli:dev .

      - name: Install Goss
        uses: e1himself/goss-installation-action@v1.2.1
        with:
          version: 'v0.4.6'

      - name: Execute Goss tests
        env:
          GOSS_FILES_STRATEGY: cp
        run: dgoss run visibilityspots/gotify-cli:dev push -t 'GitHUB CI' --token ${{ secrets.GOTIFY_TOKEN }} --url=${{ secrets.GOTIFY_URL }} dgoss test run from within github workflow

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push latest
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            visibilityspots/gotify-cli:latest
            visibilityspots/gotify-cli:${{ github.ref_name }}
          cache-from: type=registry,ref=visibilityspots/gotify-cli:buildcache
          cache-to: type=registry,ref=visibilityspots/gotify-cli:buildcache,mode=max

      - name: Create github release
        uses: ncipollo/release-action@v1
        with:
          makeLatest: true
